import Head from "next/head";
// import twemoji from "twemoji";
import EmojiCard from "../components/EmojiCard";
import emojis from "emojibase-data/en/data.json";
import Grid from "../components/Grid";
import { useState } from "react";
import SelectedEmoji from "../components/SelectedEmoji";

export default function Home(props) {
    const [emojiSize, setEmojiSize] = useState(40);
    const [selectedEmoji, setSelectedEmoji] = useState();

    function changeEmojiSize(newSize) {
        setEmojiSize(newSize);
    }

    function closeSelectedEmojiCard() {
        setSelectedEmoji(null)
    }

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                {/* <link rel="icon" href="/favicon.ico" /> */}
            </Head>
            <main>
                {emojis.length}
                <h1>Twemoji Cheatsheet</h1>

                <input
                    type="range"
                    min="16"
                    max="72"
                    step="4"
                    value={emojiSize}
                    onChange={(e) => changeEmojiSize(e.target.value)}
                />

                <Grid>
                    {emojis.map((emoji) => {
                        return (
                            <EmojiCard
                                size={emojiSize}
                                key={emoji.emoji}
                                emoji={emoji}
                                onClick={() => setSelectedEmoji(emoji)}
                            />
                        );
                    })}
                </Grid>

                {selectedEmoji && <SelectedEmoji emoji={selectedEmoji} closeFunc={closeSelectedEmojiCard} />}
            </main>
        </div>
    );
}
