import Head from "next/head";
// import twemoji from "twemoji";
import EmojiCard from "../components/EmojiCard";
import emojis from "emojibase-data/en/data.json";
import Grid from "../components/Grid";

export default function Home(props) {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                {/* <link rel="icon" href="/favicon.ico" /> */}
            </Head>

            <main>
                <Grid>
                    {emojis.map((emoji) => {
                        return (
                            <EmojiCard
                            key={emoji.emoji}
                                label={emoji.label}
                                emoji={emoji.emoji}
                            />
                        );
                    })}
                </Grid>
            </main>
        </div>
    );
}
